### ISSUE TITLE
Typo in README file URL for tutorial

### ISSUE THREAD

**Issue by peterjc** [srp33/ML-Flex#1]
http://mlflex.sourceforget.net/tutorial  --> http://mlflex.sourceforge.net/tutorial/

Source FORGET is an advert site taking advantage of people mistyping Source FORGE.

**Comment by srp33** [comment]
Thanks for noticing that. I fixed it.

**Comment by peterjc** [comment]
Confirmed, https://github.com/srp33/ML-Flex/commit/acad28d491002abeca2d4fb79f318e9c0ab9b3fd closes this issue.
